export const users = [
    {
        id: 0,
        firstName: 'John',
        lastName: 'Paul',
        email: 'jpaul@gmail.com',
        likes: 24,
        isActive: true,
    },
    {
        id: 1,
        firstName: 'Alessandra',
        lastName: 'Ambrossia',
        email: 'aambrosia@gmail.com',
        likes: 12,
        isActive: true,
    },
    {
        id: 2,
        firstName: 'Phelix',
        lastName: 'Snarley',
        email: 'psnarley@gmail.com',
        likes: 7,
        isActive: true,
    },
    {
        id: 3,
        firstName: 'Maggie',
        lastName: 'Rowland',
        email: 'mrowland@gmail.com',
        likes: 9,
        isActive: true,
    },
    {
        id: 4,
        firstName: 'Bohemian',
        lastName: 'Peter',
        email: 'bpeter@gmail.com',
        likes: 0,
        isActive: true,
    },
    {
        id: 5,
        firstName: 'Tessy',
        lastName: 'Philip',
        email: 'tessphilip@gmail.com',
        likes: 1,
        isActive: true,
    },
    {
        id: 6,
        firstName: 'Annie',
        lastName: 'Faux',
        email: 'afaux@gmail.com',
        likes: 3,
        isActive: true,
    },
    {
        id: 7,
        firstName: 'David',
        lastName: 'Blue',
        email: 'davidblue@gmail.com',
        likes: 97,
        isActive: true,
    },
]